### ISSUE TITLE
problem with pyAverager and ocn hi-res data

### ISSUE THREAD

**Issue by bertinia** [NCAR/pyAverager#10]
There is a consistent error that shows up using the pyAverager with ocn hi-resolution data. 
I'm running with these versions of the modules on yellowstone:
pyAverager/0.9.7
ASAPPyTools/0.4.3
pynio/v1.4.1
mpi4py/1.3.1

The error is:

Traceback (most recent call last):
  File "./control_ocn_slice.py", line 51, in <module>
    PyAverager.run_pyAverager(pyAveSpecifier)
  File "/glade/p/work/aliceb/sandboxes/dev/postprocessing/averager/pyAverager/pyaverager/PyAverager.py", line 28, in run_pyAverager
    return PyAverager(spec)
  File "/glade/p/work/aliceb/sandboxes/dev/postprocessing/averager/pyAverager/pyaverager/PyAverager.py", line 41, in **init**
    self.compute_averages(spec)
  File "/glade/p/work/aliceb/sandboxes/dev/postprocessing/averager/pyAverager/pyaverager/PyAverager.py", line 409, in compute_averages
    inter_comm.collect(data=md_message, tag=AVE_TAG)
  File "build/bdist.linux-x86_64/egg/asaptools/simplecomm.py", line 937, in collect
  File "Comm.pyx", line 800, in mpi4py.MPI.Comm.send (src/mpi4py.MPI.c:71596)
  File "pickled.pxi", line 182, in mpi4py.MPI.PyMPI_send (src/mpi4py.MPI.c:28829)
  File "pickled.pxi", line 83, in mpi4py.MPI._p_Pickle.dump (src/mpi4py.MPI.c:27693)
SystemError: NULL result without error in PyObject_Call
User defined signal 2
ERROR: 0031-161  EOF on socket connection with node geyser15-ib

To repeat the error, run the following stand-alone:

*******\* file control_ocn_slice.py:
# !/usr/bin/env python

from pyaverager import PyAverager, specification
#### User modify

in_dir='/glade/u/tdd/asap/bakeoff/hist/pop-0.1/'
out_dir= '/glade/scratch/aliceb/v5_rel04_BC5_ne120_t12_pop62/ocn/proc/tavg'
pref= 'v5_rel04_BC5_ne120_t12_pop62.pop.h'
htype= 'slice'
average = ['tavg:1:10','mavg:1:10']
wght= False
ncfrmt = 'netcdf4'
serial=False

var_list = ['TEMP','SALT']
mean_diff_rms_obs_dir = '/glade/p/work/mickelso/PyAvg-OMWG-obs/obs/'
region_nc_var = 'REGION_MASK'
regions={1:'Sou',2:'Pac',3:'Ind',6:'Atl',8:'Lab',9:'Gin',10:'Arc',11:'Hud',0:'Glo'}
region_wgt_var = 'TAREA'
obs_dir = '/glade/p/work/mickelso/PyAvg-OMWG-obs/obs/'
obs_file = 'obs.nc'
reg_obs_file_suffix = '_hor_mean_obs.nc'

suffix = 'nc'
clobber = True
date_pattern= 'yyyymm-yyyymm'
#### End user modify

pyAveSpecifier = specification.create_specifier(in_directory=in_dir,
                                  out_directory=out_dir,
                                  prefix=pref,
                                  suffix=suffix,
                                  date_pattern=date_pattern,
                                  hist_type=htype,
                                  avg_list=average,
                                  weighted=wght,
                                  ncformat=ncfrmt,
                                  varlist=var_list,
                                  serial=serial,
                                  clobber=clobber,
                                  mean_diff_rms_obs_dir=mean_diff_rms_obs_dir,
                                  region_nc_var=region_nc_var,
                                  regions=regions,
                                  region_wgt_var=region_wgt_var,
                                  obs_dir=obs_dir,
                                  obs_file=obs_file,
                                  reg_obs_file_suffix=reg_obs_file_suffix)

PyAverager.run_pyAverager(pyAveSpecifier)

---

... and bsub < runAvg_mpi.csh

****\* file runAvg_mpi.csh
# !/bin/csh
# BSUB -n 2
# BSUB -q geyser
# BSUB -N
# BSUB -W 4:00
# BSUB -R "span[ptile=1]"
# BSUB -P P93300606
# BSUB -o pyAve.%J.out         # output file name in which %J is replaced by the job ID
# BSUB -e pyAve.%J.err         # error file name in which %J is replaced by the job ID

module load python 
module load all-python-libs

setenv PYTHONPATH /glade/p/work/aliceb/sandboxes/dev/postprocessing/averager/pyAverager:$PYTHONPATH

mpirun.lsf ./control_ocn_slice.py

**Comment by sherimickelson** [comment]
Is fixed in v0.9.5 (will be created shortly)
